booking/urls.py
"""Defines URL patterns for homestay"""

from django.conf.urls import url
from . import views

urlpatterns = [
    # Dashboard/manage, shows upcoming reservation and all property
    url(r'^$', views.index, name='index'),
    # CRUD property # no delete, just "archive"
    url(r'^property/new/$', views.new_property, name='new_property'),
    url(r'^property/(?P<property_id>\d+)/$', views.property, name='property'),
    url(r'^property/(?P<property_id>\d+)/edit/$', views.edit_property, name='edit_property'),
    # CRUD reservation # no delete, just "archive"
    url(r'^property/(?P<property_id>\d+)/reservation/new/$', views.new_reservation, name='new_reservation'),
    url(r'^reservation/(?P<reservation_id>\d+)/$', views.reservation, name='reservation'),
    url(r'^reservation/(?P<reservation_id>\d+)/edit/$', views.edit_reservation, name='edit_reservation'),
    url(r'^reservation/(?P<reservation_id>\d+)/editstatus/$', views.edit_status_reservation, name='edit_status_reservation'),
    url(r'^reservation/(?P<reservation_id>\d+)/delete/$', views.delete_reservation, name='delete_reservation'),
    url(r'^reservation/(?P<reservation_id>\d+)/restore/$', views.restore_reservation, name='restore_reservation'),
    # JSON reservation
    url(r'^reservation/api/(?P<property_slug>[\w-]+)/$', views.reservation_json, name='reservation_json'),
    # List reservation
    url(r'^reservation/past/$', views.list_past_reservation, name='list_past_reservation'),
    url(r'^reservation/upcoming/$', views.list_upcoming_reservation, name='list_upcoming_reservation'),
    url(r'^reservation/deleted/$', views.list_deleted_reservation, name='list_deleted_reservation'),
    # Download CSV reservation
    url(r'^reservation/download-csv/$', views.download_reservation_csv, name='download_reservation_csv'),
    # Calendar for overall view of reservations
    url(r'^calendar/$', views.calendar, name='calendar'),
]

homestayapp/urls.py
"""homestayapp URL Configuration"""
from django.conf.urls import url, include
from django.contrib import admin

from . import views as main_views
from booking.views import new_customer_reservation as ncr
from booking.views import new_customer_reservation_2 as ncr2
from booking.views import list_reservation_json

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', main_views.index, name='index'),
    url(r'^app/', include('booking.urls', namespace='booking')),
    url(r'^user/', include('user.urls', namespace='user')),
    # Special link for customers only
    url(r'^(?P<property_slug>[\w-]+)/$', ncr, name='new_cust_reservation'),
    url(r'^(?P<property_slug>[\w-]+)/page2/(?P<reservation_id>\d+)/$', ncr2, name='new_cust_reservation_2'),
    # API link for listing
    url(r'^api/(?P<property_slug>[\w-]+)/$', list_reservation_json, name='list_reservation_json'),
]

user/urls.py
"""Defines URL patterns for user"""
from django.conf.urls import url
from django.contrib.auth.views import login, password_change

from . import views

urlpatterns = [
    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),
    # Login page
    url(r'^login/$', login, {'template_name': 'user/login.html'},name='login'),
    # Show settings
    url(r'^settings/$', views.settings, name='settings'),
    # Setting up password
    url(r'^password/$', password_change,{'template_name': 'user/password.html','post_change_redirect': 'index'}, name='password'),
    # Register user
    url(r'^register/$', views.register, name='register'),
]

booking/models.py
from django.db import models
from django.db.models.query import QuerySet
from datetime import time
from django.contrib.auth.models import User

class SoftDeletionQuerySet(QuerySet):
    def delete(self):
        return super(SoftDeletionQuerySet, self).update(deleted_at=timezone.now())

    def hard_delete(self):
        return super(SoftDeletionQuerySet, self).delete()

    def alive(self):
        return self.filter(deleted_at=None)
    # Reservation.all_objects.all().dead()
    def dead(self):
        return self.exclude(deleted_at=None)

class SoftDeletionManager(models.Manager):
    def __init__(self, *args, **kwargs):
        self.alive_only = kwargs.pop('alive_only', True)
        super(SoftDeletionManager, self).__init__(*args, **kwargs)

    def get_queryset(self):
        if self.alive_only:
            return SoftDeletionQuerySet(self.model).filter(deleted_at=None)
        return SoftDeletionQuerySet(self.model)

    def hard_delete(self):
        return self.get_queryset().hard_delete()

class SoftDeletionModel(models.Model):
    deleted_at = models.DateTimeField(blank=True, null=True)

    objects = SoftDeletionManager()
    all_objects = SoftDeletionManager(alive_only=False)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        self.save()

    def hard_delete(self):
        super(SoftDeletionModel, self).delete()

class Property(models.Model):
    """Details on property that is going to be made a homestay"""
    # Hidden from form
    date_added = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    owner = models.ForeignKey(User)
    slug = models.SlugField(unique=True)
    # Required
    name = models.CharField(max_length=30)
    location = models.CharField(max_length=50)
    property_type = models.CharField(max_length=20)
    max_occupant = models.IntegerField()
    normal_price = models.DecimalField(max_digits=8, decimal_places=2)
    check_in_time = models.TimeField(default=time(14,0))
    check_out_time = models.TimeField(default=time(12,0))
    bank_name = models.CharField(max_length=30)
    account_name = models.CharField(max_length=30)
    account_number = models.CharField(max_length=30)
    # Optional
    special_price = models.DecimalField(blank=True, null=True, max_digits=8, decimal_places=2)
    website = models.URLField(blank=True)
    property_description = models.TextField(blank=True)
    terms_cond = models.TextField(blank=True, verbose_name="Terms and conditions")
    # Premium
    bulk_price = models.DecimalField(blank=True, null=True, max_digits=8, decimal_places=2)
    offer_price = models.DecimalField(blank=True, null=True, max_digits=8, decimal_places=2)
    offer_ongoing = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'properties'

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

STATUS_CHOICES = (
    ('UNPAID', 'Pending payment'),
    ('PAID-DP', 'Paid down payment'),
    ('PAID-FULL', 'Paid full'),
    ('CANCELLED-NR','Cancelled no refund'),
    ('CANCELLED-PR', 'Cancelled paid refund'),
    ('COMPLETED','Completed'),
)


class Reservation(SoftDeletionModel):
    """Reservation for the homestay"""
    # Hidden from form
    date_added = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    property_obj = models.ForeignKey(Property, verbose_name='property') # customer shouldn't change this
    bank_reference = models.CharField(max_length=10,blank=True)
    # Required for customer
    customer_name = models.CharField(max_length=30, verbose_name='full name')
    customer_email = models.EmailField(verbose_name='e-mail')
    customer_phone_number = models.CharField(max_length=20, verbose_name='phone number')
    check_in_date = models.DateField()
    check_out_date = models.DateField()
    payment = models.DecimalField(max_digits=8, decimal_places=2)
    # tick box if accept terms and condition
    # accept_booking_cond = models.BooleanField()
    # Optional for customer
    customer_notes = models.TextField(blank=True)
    # For admin
    status = models.CharField(max_length=15,choices=STATUS_CHOICES,default='UNPAID')
    # Optional for admin
    notes = models.TextField(blank=True)

    def __str__(self):
        """Return a string representation of the model."""
        return u'%s %s (%s)' % (self.property_obj.name,\
                                self.check_in_date,self.id)

booking/forms.py
from django import forms
import datetime


from .models import Reservation, Property

class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = [
            # Required
            'name',
            'location',
            'property_type',
            'max_occupant',
            'normal_price',
            'check_in_time',
            'check_out_time',
            'bank_name',
            'account_name',
            'account_number',
            # Optional
            'special_price',
            'website',
            'property_description',
            'terms_cond',
            # Premium
            'bulk_price',
            'offer_price',
            'offer_ongoing',
        ]
        help_texts = {
            'check_in_time':'HH:MM:SS in 24 hours format',
            'check_out_time':'HH:MM:SS in 24 hours format',
            'special_price':'(Optional) price when demand is slightly higher eg. weekends, holiday season',
            'website':'(Optional) Enter your website URL',
            'property_description':'(Optional) Describe your property, eg. how many bedrooms, bathrooms',
            'terms_cond':'(Optional)',
            'bank_name':'Bank name eg. CIMB Bank, Maybank',
            'account_name':'Bank account name',
            'account_number':'Bank account number',
            'max_occupant':'Maximum occupant at one time',
        }

class ReservationForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     self.property_obj = kwargs.pop('property_obj')
    #     super(ReservationForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Reservation
        fields = [
            # Required for customer
            'customer_name',
            'customer_email',
            'customer_phone_number',
            'check_in_date',
            'check_out_date',
            'payment',
            # For admin
            'status',
            # Optional for admin
            'notes',
        ]
        help_texts = {
            'notes':'(Optional) Additional notes, only property owner can see this',
            'check_in_date':'YYYY-MM-DD format',
            'check_out_date':'YYYY-MM-DD format',
        }

    # No validation for Admin because contradics with edit reservation. cannot save

    # def dates_is_avaliable(self,a, b):
    #     r1,r2,r3 = (Reservation.objects.filter(property_obj=self.property_obj),)*3
    #     checkout_overlap = r1.filter(check_out_date__gt=a, check_out_date__lte=b)
    #     checkin_overlap = r2.filter(check_in_date__gte=a, check_in_date__lt=b)
    #     both_overlap = r3.filter(check_in_date__lte=a, check_out_date__gte=b)
    #     if any((checkout_overlap, checkin_overlap, both_overlap)):
    #         return False
    #     else:
    #         return True
    #
    # def clean(self):
    #     cid = self.cleaned_data['check_in_date']
    #     cod = self.cleaned_data['check_out_date']
    #     payment = self.cleaned_data['payment']
    #     if cid < datetime.date.today():
    #         raise forms.ValidationError({ "check_in_date":"Date is in the past"})
    #     if cid == cod:
    #         raise forms.ValidationError({ "check_out_date":"Check in date and check out date is the same"})
    #     if not self.dates_is_avaliable(cid, cod):
    #         raise forms.ValidationError({ "check_in_date":"Date is not avaliable",
    #                                       "check_out_date":"Date is not avaliable"})

class ReservationStatusForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['payment','status',]

class CustomerReservationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.property_obj = kwargs.pop('property_obj')
        super(CustomerReservationForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Reservation
        fields = [
            # Required for customer
            'customer_name',
            'customer_email',
            'customer_phone_number',
            'check_in_date',
            'check_out_date',
            'payment',
            # Optional for customer
            'customer_notes',
        ]
        help_texts = {
            'check_in_date':'YYYY-MM-DD format',
            'check_out_date':'YYYY-MM-DD format',
            'customer_notes': '(Optional) Send a message for your host'
        }

    # Should have just used one postgresql (if you're on it) query: select 1 from reservations r where (r.start, r.end) overlaps ($form_start, $form_end) limit 1 Uses indices, too.
    def dates_is_avaliable(self,a, b):
        r1,r2,r3 = (Reservation.objects.filter(property_obj=self.property_obj),)*3
        checkout_overlap = r1.filter(check_out_date__gt=a, check_out_date__lte=b)
        checkin_overlap = r2.filter(check_in_date__gte=a, check_in_date__lt=b)
        both_overlap = r3.filter(check_in_date__lte=a, check_out_date__gte=b)
        if any((checkout_overlap, checkin_overlap, both_overlap)):
            return False
        else:
            return True

    def verify_price(self,a,b,payment):
        normal_price = self.property_obj.normal_price
        special_price = self.property_obj.special_price if self.property_obj.special_price else normal_price
        total_days = b - a
        full_price = 0
        for x in range(total_days.days):
            if a.isoweekday()==5 or a.isoweekday()==6: # check in friday and saturday
                full_price += special_price
                a = a + datetime.timedelta(days=1)
            else:
                full_price += normal_price
                a = a + datetime.timedelta(days=1)
        return (full_price,full_price/2)

    def clean(self):
        cid = self.cleaned_data['check_in_date']
        cod = self.cleaned_data['check_out_date']
        payment = self.cleaned_data['payment']
        if cid < datetime.date.today():
            raise forms.ValidationError({ "check_in_date":"Date is in the past"})
        if cid == cod:
            raise forms.ValidationError({ "check_out_date":"Check in date and check out date is the same"})
        if not self.dates_is_avaliable(cid, cod):
            raise forms.ValidationError({ "check_in_date":"Date is not avaliable",
                                          "check_out_date":"Date is not avaliable"})
        if payment not in self.verify_price(cid,cod,payment):
            raise forms.ValidationError({"check_out_date":"Payment is neither full or down payment"})

booking/templates/booking/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Homestay App: {% block title %}{% endblock %}</title>

  {% load bootstrap3 %}
  {% load static %}
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/css/bootstraptheme.min.css' %}">
  <!-- Jquery UI CSS-->
  <link rel="stylesheet" href="{% static '/css/jquery-ui.theme.min.css' %}">

  <!-- User-Defined CSS -->
  <link rel="stylesheet" href="{% static '/css/style.css' %}">
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'booking:index' %}">Homestay App</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'index' %}">Homestay App</a>
        {% endif %}
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          {% if user.is_authenticated %}
          <li><a href="{% url 'booking:index' %}">Dashboard</a></li>
          <li><a href="{% url 'booking:calendar' %}">Calendar</a></li>
          {% else %}
          <li><a href="#">About</a></li>
          <li><a href="#">Pricing</a></li>
          <li><a href="#">FAQ</a></li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><b>Hello, {{ user.username }}</b> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'booking:download_reservation_csv' %}">Backup reservations</a></li>
              <li><a href="{% url 'booking:list_deleted_reservation' %}">Deleted reservations</a></li>
              <li><a href="{% url 'user:settings' %}">User Settings</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'user:logout' %}">Logout</a></li>
            </ul>
          </li>
          {% else %}
          <li><a href="{% url 'user:login' %}">Login</a></li>
          <li><a href="{% url 'user:register' %}">Register</a></li>
          {% endif %}
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <div class="row">
      <div class="col-md-12"><h1>{% block title2 %}{% endblock %}</h1></div>
    </div>
    <hr>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        {% block content6-1 %} {% endblock %}
      </div>
      <div class="col-md-6">
        {% block content6-2 %} {% endblock %}
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        {% block content %} {% endblock %}
      </div>
    </div>
  </div>

  <div class="container">
    <hr>
    <div class="row">
      <div class="col-md-12">
        <p class="text-center"><small>Theme by Bootswatch - <a href="{% url 'index' %}">Homestay App</a> @ 2017</small></p>
      </div>
    </div>
  </div>

  <script type="text/javascript" charset="utf-8" src="{% static '/js/jquery.min.js' %}"></script>
  <script type="text/javascript" charset="utf-8" src="{% static '/js/jquery-ui.min.js' %}"></script>
  <script type="text/javascript" charset="utf-8" src="{% static '/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" charset="utf-8" src="{% static '/js/moment.min.js' %}"></script>
  {% block js %}{% endblock %}
</body>

</html>

booking/templates/booking/edit_reservation.html
{% extends "booking/base.html" %}
{% load bootstrap3 %}
{% block title %}Edit reservation {{reservation.customer_name}} - {{reservation.property_obj.name}}{% endblock %}
{% block title2 %}Edit reservation {{reservation.customer_name}} <span class="label label-info">{{reservation.property_obj.name}}</span>{% endblock %}


{% block content6-1 %}

<form action="{% url 'booking:edit_reservation' reservation.id %}" method="post">
  {% csrf_token %}
  {% bootstrap_field form.customer_name %}
  {% bootstrap_field form.customer_email %}
  {% bootstrap_field form.customer_phone_number %}
  {% bootstrap_field form.check_in_date %}
  {% bootstrap_field form.check_out_date %}
{% endblock %}
{% block content6-2 %}
  <p>Bank ref: {{reservation.bank_reference}}</p>
  <p>Price for {{reservation.property_obj.name}}:</p>
  <ul>
    <li>Normal day: RM{{reservation.property_obj.normal_price}} per day</li>
    <li>Special day/Weekend: RM{{reservation.property_obj.special_price}} per day</li>
  </ul>
  {% bootstrap_field form.payment %}
  {% bootstrap_field form.status %}
  {% bootstrap_field form.notes %}
  {% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
  <a href="{% url 'booking:reservation' reservation.id %}" class="btn btn-default">Back</a>
</form>

{% endblock %}

{% block js %}
<script type="text/javascript">
$("#id_check_in_date").attr("autocomplete", "off");
$("#id_check_out_date").attr("autocomplete", "off");
    var timeInMs = Date.now();
    var dateFormat = "yy-mm-dd",
        from = $("#id_check_in_date")
        .datepicker({
            showButtonPanel: true,
            dateFormat: "yy-mm-dd",
        }),
        to = $("#id_check_out_date").datepicker({
            showButtonPanel: true,
            dateFormat: "yy-mm-dd",
        });
</script>
{% endblock %}

booking/templates/booking/index.html
{% extends "booking/base.html" %}
{% block title %}Dashboard{% endblock %}{% block title2 %}Dashboard <span class="pull-right" id="date" >date</span> {% endblock %}

{% block content6-1 %}
<div class="card">
  <div class="card-head">
    <h3>Currently hosting</h3>
  </div>
<div class="card-body">
  {% if now_hosting_reservations %}
    <div class="list-group">
      {% for reservation in now_hosting_reservations %}
        <a href="{% url 'booking:reservation' reservation.id %}" class="list-group-item">
          {{reservation.check_out_date|date:"j M"}} - {{reservation.customer_name}} - {{ reservation.property_obj.name }}
          {% if reservation.status == 'UNPAID' %}
            <span class="label label-danger">{{reservation.get_status_display }}</span>
          {% elif reservation.status == 'PAID-DP' %}
            <span class="label label-warning">{{reservation.get_status_display }}</span>
          {% elif reservation.status == 'PAID-FULL' or reservation.status == 'COMPLETED'  %}
            <span class="label label-success">{{reservation.get_status_display }}</span>
          {% else %}
            <span class="label label-info">{{reservation.get_status_display }}</span>
          {% endif %}
        </a>
      {% endfor %}
    </div>
  {% else %}
      <p>No reservations you are currently hosting found</p>
  {% endif %}
      <a class="btn btn-sm btn-primary"href="{% url 'booking:list_past_reservation' %}">All past reservations</a>
</div>
</div>
{% endblock %}
{% block content6-2 %}
<div class="card">
  <div class="card-head">
    <h3>Upcoming reservations </h3>
  </div>
<div class="card-body">
  {% if upcoming_reservations %}
  <div class="list-group">
      {% for reservation in upcoming_reservations %}
        <a href="{% url 'booking:reservation' reservation.id %}" class="list-group-item">
          {{reservation.check_in_date|date:"j M"}} - {{reservation.customer_name}} - {{ reservation.property_obj.name }}
          {% if reservation.status == 'UNPAID' %}
            <span class="label label-danger">{{reservation.get_status_display }}</span>
          {% elif reservation.status == 'PAID-DP' %}
            <span class="label label-warning">{{reservation.get_status_display }}</span>
          {% elif reservation.status == 'PAID-FULL' or reservation.status == 'COMPLETED' %}
            <span class="label label-success">{{reservation.get_status_display }}</span>
          {% else %}
            <span class="label label-info">{{reservation.get_status_display }}</span>
          {% endif %}
        </a>
      {% endfor %}
    </div>
      <a class="btn btn-sm btn-primary"href="{% url 'booking:list_upcoming_reservation' %}">All upcoming reservations</a>
  {% else %}
      <p>No reservations found</p>
  {% endif %}
</div>
</div>
{% endblock %}
{% block content %}
<div class="card">
  <div class="card-head">
    <h3>Property</h3>
  </div>
<div class="card-body">
  {% if properties %}
      {% for property in properties %}
      <div class="panel panel-primary">
        <div class="panel-body">
          <h4><a href="{% url 'booking:property' property.id %}"><b>{{ property.name }}</b></a></h4>
          <p>Location: {{property.location}}</p>
          <a class="btn btn-sm btn-success" href="{% url 'booking:new_reservation' property.id %}">
            New reservation</a>
          <a class="btn btn-sm btn-warning" href="{% url 'new_cust_reservation' property.slug %}" target="_blank">
            New reservation (Customer link)</a>
        </div>
      </div>
      {% endfor %}
      <p><a class="btn btn-sm btn-primary" href="{% url 'booking:new_property' %}">Add property</a></p>
  {% else %}
      <p>No properties found, add property <a class="btn btn-sm btn-primary" href="{% url 'booking:new_property' %}">here</a></p>
  {% endif %}
</div>
</div>
{% endblock %}

{% block js %}
  <script type="text/javascript">
    var now = moment().format("dddd, D MMM YYYY");;
    $("span.pull-right").html(now);
  </script>
{% endblock %}

booking/templates/booking/new_reservation.html
{% extends "booking/base.html" %}
{% load bootstrap3 %}
{% block title %}New reservation for {{property_obj.name}}{% endblock %}
{% block title2 %}New reservation for <span class="label label-primary">{{property_obj.name}}</span>{% endblock %}

{% block content6-1 %}

  <form action="{% url 'booking:new_reservation' property_obj.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_field form.customer_name %}
    {% bootstrap_field form.customer_email %}
    {% bootstrap_field form.customer_phone_number %}
    {% bootstrap_field form.check_in_date %}
    {% bootstrap_field form.check_out_date %}
    <p>*Overlapped dates will not give error</p>
{% endblock %}
{% block content6-2 %}
    <p>Price for {{property_obj.name}}:</p>
    <ul>
      <li>Normal day: RM{{property_obj.normal_price}} per day</li>
      <li>Special day/Weekend: RM{{property_obj.special_price}} per day</li>
    </ul>
    {% bootstrap_field form.payment %}
    {% bootstrap_field form.status %}
    {% bootstrap_field form.notes %}
    {% bootstrap_button "Submit" button_type="submit" button_class="btn-primary" %}
    <a href="{% url 'booking:index' %}" class="btn btn-default">Back</a>
  </form>

{% endblock %}

{% block js %}
<script type="text/javascript">
$("#id_check_in_date").attr("autocomplete", "off");
$("#id_check_out_date").attr("autocomplete", "off");
    var timeInMs = Date.now();
    var dateFormat = "yy-mm-dd",
        from = $("#id_check_in_date")
        .datepicker({
            showButtonPanel: true,
            dateFormat: "yy-mm-dd",
        }),
        to = $("#id_check_out_date").datepicker({
            showButtonPanel: true,
            dateFormat: "yy-mm-dd",
        });
</script>

{% endblock %}

booking/templates/booking/reservation.html
{% extends "booking/base.html" %}

{% block title %}Reservation {{reservation.customer_name}} - {{reservation.property_obj.name}}{% endblock %}
{% block title2 %}Reservation {{reservation.customer_name}} <span class="label label-info">{{reservation.property_obj.name}}</span>{% endblock %}

{% block content6-1 %}
<ul class="list-group">
  <li class="list-group-item">Name: <b>{{reservation.customer_name}}</b></li>
  <li class="list-group-item">Email: <b>{{reservation.customer_email}}</b></li>
  <li class="list-group-item">Phone number: <b>{{reservation.customer_phone_number}}</b></li>
  <li class="list-group-item">Bank ref: <b>{{reservation.bank_reference}}</b></li>
  <li class="list-group-item">Payment: <b>{{reservation.payment}}</b></li>
  <li class="list-group-item">Status: <b>{{ reservation.get_status_display }}</b>  <a class="btn btn-sm btn-primary"href="{% url 'booking:edit_status_reservation' reservation.id %}">Edit Status</a>
</li>
</ul>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="col-sm-6">
      <p>Check in: <b>{{reservation.check_in_date|date:"D, j M"}}</b></p>
    </div>
    <div class="col-sm-6">
      <p>Check out: <b>{{reservation.check_out_date|date:"D, j M"}}</b></p>
    </div>
  </div>
</div>

{% endblock %}
{% block content6-2 %}
  <ul class="list-group">
    <li class="list-group-item">Customer notes: {{reservation.customer_notes}}</li>
    <li class="list-group-item">Notes: {{reservation.notes}}</li>
    <li class="list-group-item">Date added: {{reservation.date_added}}</li>
  </ul>
  <a class="btn btn-warning"href="{% url 'booking:edit_reservation' reservation.id %}">Edit all</a>
  <a class="btn btn-danger" href="{% url 'booking:delete_reservation' reservation.id%}">Delete</a>
{% endblock %}