homestayapp/urls.py
"""homestayapp URL Configuration"""
from django.conf.urls import url, include
from django.contrib import admin

from . import views as main_views
from booking.views import new_customer_reservation as ncr
from booking.views import new_customer_reservation_2 as ncr2
from booking.views import list_reservation_json

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', main_views.index, name='index'),
    url(r'^app/', include('booking.urls', namespace='booking')),
    url(r'^user/', include('user.urls', namespace='user')),
    # Special link for customers only
    url(r'^(?P<property_slug>[\w-]+)/$', ncr, name='new_cust_reservation'),
    url(r'^(?P<property_slug>[\w-]+)/page2/(?P<reservation_id>\d+)/$', ncr2, name='new_cust_reservation_2'),
    # API link for listing
    url(r'^api/(?P<property_slug>[\w-]+)/$', list_reservation_json, name='list_reservation_json'),
]

user/urls.py
"""Defines URL patterns for user"""
from django.conf.urls import url
from django.contrib.auth.views import login, password_change

from . import views

urlpatterns = [
    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),
    # Login page
    url(r'^login/$', login, {'template_name': 'user/login.html'},name='login'),
    # Show settings
    url(r'^settings/$', views.settings, name='settings'),
    # Setting up password
    url(r'^password/$', password_change,{'template_name': 'user/password.html','post_change_redirect': 'index'}, name='password'),
    # Register user
    url(r'^register/$', views.register, name='register'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Owner(models.Model):
    # Hidden from form
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    # Superadmin only
    is_premium = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    # Required
    full_name = models.CharField(max_length=150)
    phone_number = models.CharField(max_length=20, verbose_name='phone number')
    # Optional
    company_name = models.CharField(max_length=150,blank=True)
    company_address = models.CharField(max_length=400,blank=True)
    # TODO: bank acc dan lain2

    def __str__(self):
        """Return a string representation of the model."""
        return u'%s %s (%s)' % (self.full_name,
                                self.company_name,self.id)

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Owner

class OwnerForm(forms.ModelForm):
    class Meta:
        model = Owner
        fields = [
            # Required for customer
            'full_name',
            'phone_number',
            # Optional for customer
            'company_name',
            'company_address'
        ]
        labels = {
            'company_name': 'Company name(optional)',
            'company_address': 'Company address(optional)',
        }

class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = [
            "email",
            "username",
            "password1",
            "password2"
         ]

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "email",
            "username",
         ]

    def save(self, commit=True):
        user = super(UserChangeForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

user/views.py
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, login, authenticate, update_session_auth_hash
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Owner
from .forms import OwnerForm, UserCreationForm, UserChangeForm


def logout_view(request):
    """Log the user out"""
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display blank registration form
        form = UserCreationForm()
        owner_form = OwnerForm()
    else:
        # Process completed form
        form = UserCreationForm(data=request.POST)
        owner_form = OwnerForm(data=request.POST)

        if form.is_valid() and owner_form.is_valid():
            new_user = form.save()
            new_owner = owner_form.save(commit=False)
            new_owner.user = new_user
            new_owner.save()
            # Log the user in and then redirect to home page.
            authenticate_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, authenticate_user)
            return HttpResponseRedirect(reverse('booking:index'))
    context = {'form': form, 'owner_form': owner_form}
    return render(request, 'user/register.html', context)

@login_required
def settings(request):
    """Edit settings for a user"""
    user = request.user
    owner = Owner.objects.get(user=user)

    if request.method != 'POST':
        # Display blank registration form
        form = UserChangeForm(instance=user)
        owner_form = OwnerForm(instance=owner)
    else:
        # Process completed form
        form = UserChangeForm(data=request.POST,instance=user)
        owner_form = OwnerForm(data=request.POST,instance=owner)

        if form.is_valid() and owner_form.is_valid():
            new_user = form.save()
            new_owner = owner_form.save(commit=False)
            new_owner.user = new_user
            new_owner.save()
            return HttpResponseRedirect(reverse('booking:index'))
    context = {'form': form, 'owner_form': owner_form}
    return render(request, 'user/settings.html', context)

user/templates/user/login.html
{% extends "booking/base.html" %}
{% load bootstrap3 %}

{% block title %}Login{% endblock %}{% block title2 %}Login{% endblock %}

{% block content6-1 %}
  {% if form.errors %}
  <p>Your username and password didn't match. Please try again</p>
  {% endif %}
  <form action="{% url 'user:login' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit"  name="submit" class="btn btn-primary">Login</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'booking:index' %}">
  </form>
{% endblock %}

user/templates/user/password.html
{% extends "booking/base.html" %}
{% load bootstrap3 %}
{% block title %}Change Password{% endblock %}{% block title2 %}Change Password{% endblock %}

{% block content6-1 %}
  <form method="post" action="{% url 'user:password' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" name="submit" class="btn btn-primary">Save</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'booking:index' %}" />
  </form>
{% endblock %}

user/templates/user/register.html
{% extends "booking/base.html" %}
{% load bootstrap3 %}
{% block title %}Register{% endblock %}{% block title2 %}Register{% endblock %}

{% block content6-1 %}
  <form method="post" action="{% url 'user:register' %}">
    {% csrf_token %}
    {% bootstrap_form owner_form %}
    {% bootstrap_form form %}
    {% buttons %}
      <button  type="submit" name="submit" class="btn btn-primary">Register</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'booking:index' %}" />
  </form>
{% endblock %}

user/templates/user/settings.html
{% extends "booking/base.html" %}
{% load bootstrap3 %}
{% block title %}Settings{% endblock %}{% block title2 %}Settings{% endblock %}

{% block content6-1 %}
  <form method="post" action="{% url 'user:settings' %}">
    {% csrf_token %}
    {% bootstrap_form owner_form %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" name="submit" class="btn btn-primary">Save</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'booking:index' %}" />
  </form>
  <p><a href="{% url 'user:password' %}" class="btn btn-default">Change password</a></p>
{% endblock %}